#' @importFrom ncbi taxonDBConnect geneidDBConnect
#' @importFrom ncbi createTaxonDB createGeneidDB updateTaxonDB updateGeneidDB
NULL

.taxonomy_db.sql <- '
  CREATE TABLE taxonomy(
          query_id        INTEGER,
          tax_id          TEXT,
          scientific_name	TEXT,
          rank            TEXT,
          PRIMARY KEY (query_id),
          FOREIGN KEY (query_id) REFERENCES query (query_id)
  );
  CREATE INDEX Ftaxonomy_query ON taxonomy (query_id);
  CREATE INDEX Ftaxonomy_tax ON taxonomy (tax_id);
  CREATE INDEX Ftaxonomy_tax_hit_query ON hsp (query_id, hit_id, tax_id);
  '

taxonomy_db.sql <- function() {
  .taxonomy_db.sql
}

#' Create or connect to a local install of NCBI Taxonomy database
#'
#' @description Create, update or connect to a local installation of the NCBI 
#'             Taxonomy Database. The Connection object is returned as a list 
#'             of connections to \code{'taxon.db'} and \code{'geneid.db'}. 
#'
#' @param db_path Parent directory of the taxonomy databases \bold{taxon.db}
#' and \bold{geneid.db}. This path should be permanently configured by setting
#' the option \code{ncbi.taxonomy.path}. 
#'
#' @rdname taxonDB
#' @export
connectTaxonDB <- function(db_path = getOption("ncbi.taxonomy.path")) {
  list(taxon_db = taxonDBConnect(db_path), 
       geneid_db = geneidDBConnect(db_path))
}

#' @rdname taxonDB
#' @export
createTaxonDB <- function(db_path = getOption("ncbi.taxonomy.path")) {
  ncbi::createTaxonDB(db_path)
  ncbi::createGeneidDB(db_path)
}

#'@rdname taxonDB
#'@export
updateTaxonDB <- function(db_path = getOption("ncbi.taxonomy.path")) {
  ncbi::updateTaxonDB(db_path)
  ncbi::updateGeneidDB(db_path)
}

#' create, update or drop a SQL-Table
#' 
#'@description wrapper for database manipulation in SQL
#'
#'@param blast_db connection to a database
#'@param tbl name of table
#'@param sql string with table scheme
#'
#' @rdname db-functions
#' @export 
createTable <- function(db, tbl, tbl_scheme) {
  if (db %has_tables% tbl) {
    # table already exists -> delete and rewrite
    dropTable(db, tbl)
  }
  db_query(db, tbl_scheme)
}

#'@param df data.frame generated by assignTaxon()
#'
#'@rdname db-functions
#'@export
updateTable <- function(db, tbl, df, ...) {
 db_bulk_insert(db, tbl, df, ...)
}

#'@rdname db-functions
#'@export
dropTable <- function(db, tbl) {
  db_query(db, paste("DROP table", tbl))
}

