#'@importFrom rmisc db_query
#'@importFrom rmisc db_bulk_insert
#'@importFrom rmisc "%has_tables%"
NULL

taxonomy_create.sql <- 'CREATE TABLE taxonomy(
                        query_id        INTEGER,
                        hit_id          INTEGER,
                        gene_id         TEXT,
                        accession       TEXT,
                        tax_id          TEXT,
                        scientific_name	TEXT,
                        rank            TEXT,
                        PRIMARY KEY (hit_id),
                        FOREIGN KEY (query_id) REFERENCES query (query_id),
                        FOREIGN KEY (hit_id) REFERENCES query (hit_id)
                );
                CREATE INDEX Ftaxonomy_query ON taxonomy (query_id);
                CREATE INDEX Ftaxonomy_hit ON taxonomy (hit_id);
                CREATE INDEX Ftaxonomy_tax ON taxonomy (tax_id);
                CREATE INDEX Ftaxaonomy_tax_hit_query ON hsp (query_id, hit_id, tax_id);
                '

taxonomy_drop.sql <- 'DROP TABLE taxonomy;'

#' establish a connection to taxonomy database
#'
#'@description establish a list of connection objects to the local installations of the
#'taxon.db and geneid.db files
#'
#'@param path_to_db location of the taxonomy db
#'
#'@rdname connectTaxonDB
#'
#'@importFrom ncbi taxonDBConnect
#'@importFrom ncbi geneidDBConnect
#'@export
connectTaxonDB <- function(path_to_db) {
  list(taxon_db=taxonDBConnect(path_to_db),geneid_db=geneidDBConnect(path_to_db))
}

#'extend and update the blast database
#'
#'@description the orignial blast database generated from a XML file will be extended and updated by
#'a taxonomy table containing informations about the taxonomical classification for 
#'a specific query.
#'
#'\section{Slots:}{
#'  \describe{
#'    \item{\code{query_id}:}{identifier for the query}
#'    \item{\code{hit_id}:}{identifier for the best hit used for classification}
#'    \item{\code{gene_id}:}{blast identifier for a sequence}
#'    \item{\code{accession}:}{blast identifier for a sequence}
#'    \item{\code{tax_id}:}{identifier in the ncbi taxonomy}
#'    \item{\code{scientific_name}:}{name in the ncbi taxonomy}
#'    \item{\code{rank}:}{rank in the ncbi taxonomy}
#'    \item{\code{superkingdom}:}{Bacteria, Eukaryota or unclassified}
#'  }
#'}
#'@param blastDB \code{blastReportDB} object
#'
#'@rdname TaxonomyTable
#'@export
createTaxonomyTable <- function(blast_db) {
  if (blast_db %has_tables% 'taxonomy') {
    # table already exists -> delete and rewrite
    db_query(blast_db,taxonomy_drop.sql)
  }
  db_query(blast_db,taxonomy_create.sql)
}

#'@param df data.frame generated by assignTaxon()
#'
#'@rdname TaxonomyTable
#'@importFrom rmisc db_bulk_insert
#'@export
updateTaxonomyTable <- function(blast_db,df) {
  db_bulk_insert(blast_db,"taxonomy",df)
}

#' partionate the blast database by classifier
#' 
#' @description select all entries in the blast database by matching a classifier (e.g. 
#' superkingdom) and create a new database with the selected values. original database
#' will be untouched
#' 
#' @param blastDB \code{blastReportDB} object
#' @param classifier values for partioning
#' 
#' @note make more general
#' 
#' @importFrom RSQLite dbListFields
#' @importFrom RSQLite dbListTables
#' @importFrom rmisc db_create
#' @rdname createNewDatabase
#' @export
createNewDatabase <- function(path_to_new_db,classifier){
  if (!tolower(classifier) %in% c('bacteria','eukaryota','unclassified')) {
    stop(paste(classifier," must be in 'bacteria','eukaryota','unclassified'"))
  }
  #con <- db_create(paste0(path_to_new_db,,classifier,'.db'),dbSchema=blastr:::blast_db.sql)
  #con
  #con <- blastr:::new_blastReportDB(con)
  #con
  #createTaxonomyTable(blastDB=con)
  #dbListTables(con)
  #dbListFields(con,'query')
  #dbListFields(con,'hit')
  #dbListFields(con,'hsp')
  #dbListFields(con,'taxonomy')
}

