#'@importFrom rmisc db_query
#'@importFrom rmisc db_bulk_insert
#'@importFrom rmisc "%has_tables%"
#'@importFrom ncbi taxonDBConnect
#'@importFrom ncbi geneidDBConnect
NULL

taxonomy_create.sql <- 'CREATE TABLE taxonomy(
                        query_id        INTEGER,
                        hit_id          INTEGER,
                        gene_id         TEXT,
                        accession       TEXT,
                        tax_id          TEXT,
                        scientific_name	TEXT,
                        rank            TEXT,
                        PRIMARY KEY (hit_id),
                        FOREIGN KEY (query_id) REFERENCES query (query_id),
                        FOREIGN KEY (hit_id) REFERENCES query (hit_id)
                );
                CREATE INDEX Ftaxonomy_query ON taxonomy (query_id);
                CREATE INDEX Ftaxonomy_hit ON taxonomy (hit_id);
                CREATE INDEX Ftaxonomy_tax ON taxonomy (tax_id);
                CREATE INDEX Ftaxaonomy_tax_hit_query ON hsp (query_id, hit_id, tax_id);
                '

#' establish a connection to taxonomy database
#'
#'@description establish a list of connection objects to the local installations of the
#'taxon.db and geneid.db files
#'
#'@param path_to_db location of the taxonomy db
#'
#'@rdname connectTaxonDB
#'
#'@export
connectTaxonDB <- function(path_to_db) {
  list(taxon_db = taxonDBConnect(path_to_db), 
       geneid_db = geneidDBConnect(path_to_db))
}

#'extend and update the blast database
#'
#'@description the orignial blast database generated from a XML file will be extended and updated by
#'a taxonomy table containing informations about the taxonomical classification for 
#'a specific query.
#'
#'\section{Slots:}{
#'  \describe{
#'    \item{\code{query_id}:}{identifier for the query}
#'    \item{\code{hit_id}:}{identifier for the best hit used for classification}
#'    \item{\code{gene_id}:}{blast identifier for a sequence}
#'    \item{\code{accession}:}{blast identifier for a sequence}
#'    \item{\code{tax_id}:}{identifier in the ncbi taxonomy}
#'    \item{\code{scientific_name}:}{name in the ncbi taxonomy}
#'    \item{\code{rank}:}{rank in the ncbi taxonomy}
#'    \item{\code{superkingdom}:}{Bacteria, Eukaryota or unclassified}
#'  }
#'}
#'@param blastDB \code{blastReportDB} object
#'
#'@rdname TaxonomyTable
#'@export 
createTaxonomyTable <- function() {
  print("DEPRECATED")
}

createTable <- function (blast_db, tbl, tbl_scheme) {
  if (blast_db %has_tables% tbl) {
    # table already exists -> delete and rewrite
    dropTable(blast_db, tbl)
  }
  db_query(blast_db,tbl_scheme)
}

#'@param df data.frame generated by assignTaxon()
#'
#'@rdname TaxonomyTable
#'@export
updateTable <- function (blast_db, tbl, df) {
  db_bulk_insert(blast_db, tbl, df)
}

dropTable <- function (blast_db, tbl) {
  db_query(blast_db, paste("DROP table",tbl))
}

