# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bind_list <- function(L, n_col, col_classes) {
    .Call('metaR_bind_list', PACKAGE = 'metaR', L, n_col, col_classes)
}

